env: academy_pass_and_shoot_with_keeper # google research football

env_args:
  dense_reward: False
  write_full_episode_dumps: False
  write_goal_dumps: False
  dump_freq: 1000
  render: False
  n_agents: 2
  time_limit: 150
  time_step: 0
  obs_dim: 22
  env_name: "academy_pass_and_shoot_with_keeper"
  stacked: False
  representation: "simple115v2"
  rewards: "scoring"
  logdir: "football_dumps"
  write_video: False
  number_of_right_players_agent_controls: 0
  seed: 0
  reward_sparse: False
  reward_max: 10
  reward_positive: False
  reward_reset_punish: True

batch_size: 8
test_greedy: True
test_nepisode: 32
test_interval: 10000
log_interval: 10000
runner_log_interval: 10000
learner_log_interval: 10000
t_max: 5050000
obs_agent_id: False
obs_last_action: True
runner: "grfepisode"